# Generated by Django 5.1.2 on 2024-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
