# Generated by Django 5.1.2 on 2024-10-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0002_member_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
